name: agrovision_mobile
description: "AgroVision Mobile - Smart Agricultural Management Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.3.3
  connectivity_plus: ^4.0.2
  
  # Local Storage
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  
  # Firebase Services
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5

  # Utils
  intl: ^0.18.1
  logger: ^2.0.1
  json_annotation: ^4.8.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  mock_web_server: ^5.0.0-nullsafety.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
