// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSJ_gW5ApNzHTX3Re-N24SDyxLfiX3tk',
    appId: '1:703235345618:web:46ae1be9d6fae81b3af10b',
    messagingSenderId: '703235345618',
    projectId: 'agro-vision-20c05',
    authDomain: 'agro-vision-20c05.firebaseapp.com',
    storageBucket: 'agro-vision-20c05.firebasestorage.app',
    measurementId: 'G-FCLYR78QHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7AtpM-FcVqNRt_rbocENk6o7CdAEUPNU',
    appId: '1:703235345618:android:572d53a18c4090043af10b',
    messagingSenderId: '703235345618',
    projectId: 'agro-vision-20c05',
    storageBucket: 'agro-vision-20c05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaCD6v703YtnPqWrZnnudC9Ee13BOctNU',
    appId: '1:703235345618:ios:7d53180d4e8928d53af10b',
    messagingSenderId: '703235345618',
    projectId: 'agro-vision-20c05',
    storageBucket: 'agro-vision-20c05.firebasestorage.app',
    iosBundleId: 'com.dawell.agrovision.agrovisionMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaCD6v703YtnPqWrZnnudC9Ee13BOctNU',
    appId: '1:703235345618:ios:2139084830d7d0393af10b',
    messagingSenderId: '703235345618',
    projectId: 'agro-vision-20c05',
    storageBucket: 'agro-vision-20c05.firebasestorage.app',
    iosBundleId: 'com.settingforios.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSJ_gW5ApNzHTX3Re-N24SDyxLfiX3tk',
    appId: '1:703235345618:web:98499182e13b56183af10b',
    messagingSenderId: '703235345618',
    projectId: 'agro-vision-20c05',
    authDomain: 'agro-vision-20c05.firebaseapp.com',
    storageBucket: 'agro-vision-20c05.firebasestorage.app',
    measurementId: 'G-C0CPFZBWEK',
  );

}